version: "3"
services:

  release-belt:
    build:
      context: .
      dockerfile: Dockerfile
    image: ztj1993/release-belt:latest
    hostname: release-belt
    container_name: release-belt
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/srv/releases
    expose:
      - 80/tcp
    ports:
      - 8081:80
